homepage:
  path: /
  controller: App\Controller\HomeController::homepage

registrationRules:
  path: /support/reglement-d-inscription
  controller: App\Controller\HomeController::registrationRules

legalNotices:
  path: /support/mentions-legales/
  controller: App\Controller\HomeController::legalNotices

inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::index

login:
  path: /login
  controller: App\Controller\AdminController::login

logout:
  path: /logout

admin:
  path: /admin
  controller: App\Controller\AdminController::index